Fix test due to deprecated
1) ThreadStorageManagerTest::testGetThreadEmailAttachment
ErrorException: ImapConnection-errorHandler: Creation of dynamic
property ThreadStorageManagerTest::$testEmailId is deprecated